# General
CONTACT_EMAIL=""
DATA_LAKE_BUCKET=""

# Pinecone 
PINECONE_API_KEY=""
PINECONE_REGION="us-east-1"
PINECONE_IMPORT_URI=""
PINECONE_INTEGRATION_ID=""
PINECONE_EMBEDDING_MODEL="multilingual-e5-large"
PINECONE_PROD_INDEX=""

# AWS
BEDROCK_EMBEDDING_MODEL="cohere.embed-english-v3"
BEDROCK_TEXT_MODEL="anthropic.claude-3-haiku-20240307-v1:0"
AWS_REGION="us-east-1"
